### ISSUE TITLE
Sourcemaps?

### ISSUE THREAD

**Issue by girvo** [hostnet/webpack-bundle#13]
Hey there, quick question: does this bundle support generation of sourcemaps through WebPack? Leveraging Babel is a brilliant idea, as is the ability to leverage the numerous WebPack plugins, but giving up sourcemaps when in development would be a shame. 

Also, just to clarify, if I have a project with a number of bundles, within the Javascript I can just `require('@ExampleBundle/some.js')` within, say `AnotherBundle/Resources/assets/main.js`?

**Comment by haroldiedema** [comment]
Hi girvo,

Sourcemap support isn't currently builtin, but it could easily be built in by modifying the BabelLoader class, since all it does is generate javascript code. Personally I didn't play around with sourcemaps yet, so I honestly have no idea what the configuration of that should look like. If you know how to do this, feel free to send a PR. If not, then I'll have a look at it next week.

As for your second question, that is correct. You can indeed use bundle short-names throughout all your javascript files in your application. This works for including all types of assets, not just javascript files.

For example: `require('@AcmeBundle/some-image.png')` would work just as well :+1:

**Comment by iltar** [comment]
Closing this issue as this depends on the loader/plugin etc to supply this support.
