### ISSUE TITLE
Adding own loaders via "hostnet_webpack.config_extension" impossible

### ISSUE THREAD

**Issue by akomm** [hostnet/webpack-bundle#26]
The services are loaded in the WebpackExtension, making it impossible to add own loaders - e. G. sass - using the "hostnet_webpack.config_extension" tag. Is there any problem moving it into a compiler pass?

See loading in WebpackExtension:

https://github.com/hostnet/webpack-bundle/blob/4fed1aa1d40e4f6c369396e9a31b2a85ade24488/src/Bundle/DependencyInjection/WebpackExtension.php#L33

*edit*

It only does not work, when you register your services via Extension, so they are not "visible" when WebpackExtension is loading the config-extensions.

**Comment by iltar** [comment]
I think a bundle should explicitly register loaders in the same way the security bundle tells you to: https://github.com/symfony/symfony/blob/c8475c938d55eb8e7c7df53177b346012b39159c/src/Symfony/Bundle/SecurityBundle/SecurityBundle.php#L43

**Comment by iltar** [comment]
@akomm I think the following approach would be interesting:
```php
// WebpackExtension
public function addPlugin(PluginInterface $plugin);
public function addLoader(LoaderInterface $loader);
```
This way the loaders and plugins can be added in the bundle load

```php
    // your bundle
    public function build(ContainerBuilder $container)
    {
        $extension = $container->getExtension('wevpack');
        $extension->addLoader(new SassLoader());
        $extension->addPlugin(new SomePlugin());
    }
```

The only problem existing is that with this setup, a rewrite is necessary as of the constructors currently requiring config. A quick solution which might work in-between, is to have the Plugins/Loaders `::class` here instead.

In the ideal situation I would minimize the run-time configuration, because of things like this:
```php
    protected function getHostnetWebpack_Bridge_ConfigGeneratorService()
    {
        $this->services['hostnet_webpack.bridge.config_generator'] = $instance = new \Hostnet\Component\Webpack\Configuration\ConfigGenerator();
        $instance->addExtension($this->get('hostnet_webpack.config.output'));
        $instance->addExtension($this->get('hostnet_webpack.config.resolve'));
        $instance->addExtension($this->get('hostnet_webpack.config.resolve_loader'));
        $instance->addExtension($this->get('hostnet_webpack.loader.css'));
        $instance->addExtension($this->get('hostnet_webpack.loader.url'));
        $instance->addExtension($this->get('hostnet_webpack.loader.less'));
        $instance->addExtension($this->get('hostnet_webpack.loader.babel'));
        $instance->addExtension($this->get('hostnet_webpack.plugin.define'));
        return $instance;
    }
```

This could all be done compile time already, effectively reducing the container overhead. This is the only place where the services are injected and required, so the ConfigGenerator knows what to generate, which is called from the [Compiler](https://github.com/hostnet/webpack-bundle/blob/a9dadee1f72545e99fa236b51cb2bd6f5229af83/src/Component/Asset/Compiler.php#L96-L99):
```php
        // Write the webpack configuration file.
        file_put_contents(
            $this->cache_dir . DIRECTORY_SEPARATOR . 'webpack.config.js',
            $this->generator->getConfiguration()
        );
```

In theory the webpack.config.js could already be generated during container compilation which would make it possible to ditch the Plugin/Configuration services and have them compile time only. What are your opinions @haroldiedema / @yannickl88 ?

This whole issue is something I'd like to have tackled before releasing `1.0`.

**Comment by haroldiedema** [comment]
Ideally I would rather see tagged services which implement either a `PluginInterface` or a `LoaderInterface`. I thought this already worked properly?

If you make sure the webpack bundle is the __last element__ of your bundles array in the `AppKernel`, then it _should_ work just fine.

If not, feel free to go with your proposal, @iltar.

**Comment by akomm** [comment]
I wonder about your bundle reordering proposal in AppKernel. As far as I know the order does not matter. Every extension get an empty container passed in. After all extensions has been loaded, their containers are merged with the "global" one. So order should not change anything.

I'v tried it though, just to be sure. As expected: it did fix the problem.

**Comment by iltar** [comment]
@akomm @mariusbalcytis is this issue resolved now?

**Comment by hboomsma** [comment]
No response

**Comment by akomm** [comment]
Strange, got the notification for closed on github, but not the comment from 2015. The issue is resolved. Thank you!
