### ISSUE TITLE
Hot reload feature

### ISSUE THREAD

**Issue by lunetics** [hostnet/webpack-bundle#39]
It's possible to have a hot reload feature for webpack. Can that be integrated? @haroldiedema 

see: 
http://webpack.github.io/docs/webpack-dev-server.html

http://www.jonathan-petitcolas.com/2015/05/15/howto-setup-webpack-on-es6-react-application-with-sass.html

**Comment by haroldiedema** [comment]
Hi lunetics, 

Thanks for taking the time to bring this up.

I've looked into integrating this in the intial release, but I haven't found any way to properly integrate this in a Symfony app. The reason for this is because the actual URL's of static (compiled) resources need to be changed which may cause twig files to be cached with the wrong URL's in Symfony.

Something that *can* be done however, is making some kind of toggle feature that effectively disables the cache-tracking feature while working in *dev mode*. This way, all resources could be recompiled on page refreshes. The downside of this however, is that it will drasticly increase loading times of pages depending on how large your application is.

However, since all assets are tracked by this bundle, any change made to source files will trigger webpack to recompile everything whenever you refresh the page. So I'm kind of curious why you would need this feature in the first place, since it's already being taken care of.

Either way, neither of these features (hotreload and no-cache) made it in for both their own (obvious) reasons.

**Comment by lunetics** [comment]
Hi, 

Currently playing around with that for a few hours, almost got it working.

The Problem is e.g. i got 2 entry points, app.js and one e.g. for bootstrap.js

so if i change something inside of one scss, everything will be recompiled I (Compile Reason: .../src/AppBundle/Resources/assets/bootstrap/bootstrap.scss" has been modified.) That takes ~ 1840 ms analyze, 4893 compile = total 6733 ms time. That's way too long.

Having the webpack-dev server, it's under a second + the css will be replaced inline (without page refresh). So we save also the symfony debug refresh.

I think it'll  be fairly easy to have some additional config with (Inline mode)

* path to webpack-dev-server.js node module (or by default take the "%node_modules%/webpack-dev-server/bin/webpack-dev-server.js) as binary file
* host / port config (which will be taken for the webpack-dev-server)
* webpack-dev-server config (can be shared e.g. for a command + the assets)

And if dev-server enabled, the assets (src tag) will be just prependet by the dev server "http://my.host:8080/compiled/foo.js" instead of "/compiled/foo.js" 
+ ONE additional webpack-dev-server.js script src tag.

the dev server also has a --content-base option and will act as webserver for assets, where it will server updated assets from in-memory and fallbacks to the filesystem.

btw, is there an easy way to have an additional "target" in an array for all entry points like in the following example entry point? I think that'll make it even easier

```json
module.exports = {
    entry: {
        helloWorld: [
            'webpack-dev-server/client?http://localhost:8080',
            './js/helloworld.js',
        ]
    }
    // ...
};
```

**Comment by lunetics** [comment]
Just playing around and seeing the output.public_path cannot differ from the path? why is that, i wanted to try to give the dev-server ip/port (CDN LIKE?) but it's not allowed by configuration. any special cause?

**Comment by iltar** [comment]
Currently there's a limitation where the web directory is determined based on the path - public path. I'm not sure what the webpack configuration allows you to do but symfony doesn't allow a proper configuration here as they don't provide a web_dir param.

If you know how it should work exactly, we could extract that logic to a simple config option and you can use both loose again. This was more a fix for our specific use-case.

**Comment by haroldiedema** [comment]
@lunetics,

If you manage to get this working, please provide a pull request so we can see how this impacts the integration in symfony for ourselves. The webpack-compiler that is called by our bundle needs to be aware that the dev-server is running so it doesn't recompile things by itself.

I'm very curious to see how you've tackled the caching problem.

**Comment by iltar** [comment]
Closing this as hot reload won't work as is with this bundle
