### ISSUE TITLE
Removal of useful configuration options in #07d9e3a

### ISSUE THREAD

**Issue by zalox** [hostnet/webpack-bundle#58]
Hi, 

I'm trying to use this project, but I have a somewhat different setup than the standard settings for assets and javascript sources. I was wondering why these configuration options was removed, or if could they be reintroduced?

https://github.com/hostnet/webpack-bundle/commit/07d9e3a8902a3692571f0fdc010a3af2b33b2d53#diff-4013e02b8b5330974727f71029e9eb1aL22

**Comment by haroldiedema** [comment]
Hi Zalox,

Apologies for the late response. I'm currently on holidays.

These settings were removed from the bundle to enforce people to use one standard location for assets, just like the `public` directory in `Resources`. Because typical usages for assets is to bundle them in symfony bundles, having custom application-wide directories would cause alot of incompatibilties between vendor-packages.

**Comment by zalox** [comment]
Hi, thanks for your response!

So there aren't any features that rely on enforcing the folder structure?

**Comment by haroldiedema** [comment]
Apart from the output folders, no.

I personally have no intention of ever re-introducing the ability to change the location of the `assets` directory ever again since it will cause compatibility issues when using third-party bundles that rely on the default folder structure.

**Comment by zalox** [comment]
Thanks again, I managed to change the default folder with a compiler pass. Now everything is working smoothly!
